## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import os
import Options
from waflib.Errors import WafError

def build(bld):
    # Build the Switch module
    mirage = bld.create_ns3_module('mirage', ['internet'])
    mirage.source = [
        'helper/mirage-helper.cc', 
        'model/mirage-net-device.cc',
        ]

    mirage_test = bld.create_ns3_module_test_library('mirage')
    mirage_test.source = [
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'mirage'
    headers.source = [
        'helper/mirage-helper.h', 
        'model/mirage-net-device.h',
        ]

    if bld.env['ENABLE_EXAMPLES']:
        bld.add_subdirs('examples')
